# Generated by Django 5.0.7 on 2024-07-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('one', 'Kursatilsin'), ('two', 'Kursatilmasin')], default=1, max_length=14),
        ),
    ]
